---
- hosts: all
  become: true

  vars:
    brew_user: brew

  tasks:
    - name: Install SSH key for brew user
      authorized_key:
        key=https://github.com/speshak.keys
        user={{brew_user}}

    - name: Install packages
      apt:
        name={{item}}
        state=present
        update_cache=yes
      with_items:
        - build-essential
        - cmake
        - qt5-default
        - libqt5sql5-psql
        - libqt5svg5-dev
        - libqt5webkit5-dev
        - libqt5multimedia5
        - libqt5multimedia5-plugins
        - qtmultimedia5-dev
        - qttools5-dev
        - qttools5-dev-tools
        - postgresql-9.5
        - python-psycopg2
        - vim
        - git
        - autofs
      tags:
        - install
        - packages

    - name: Pull in dotfiles
      git:
        repo=https://github.com/speshak/dotfiles.git
        dest=/home/{{brew_user}}/.dotfiles
      become: false
      tags:
        - install
        - dotfiles

    - name: Install dotfiles
      command: /home/{{brew_user}}/.dotfiles/script/bootstrap
      become: false
      tags:
        - install
        - dotfiles


    - name: Clone brewtarget dev repo
      git:
        repo=https://github.com/Brewtarget/brewtarget
        dest=/home/{{brew_user}}/brewtarget
      become: false
      tags:
        - brewtarget

    - name: Configure brewtarget build
      command: /home/{{brew_user}}/brewtarget/configure
        chdir=/home/{{brew_user}}/brewtarget
        creates=/home/{{brew_user}}/brewtarget/build/Makefile
      become: false
      tags:
        - brewtarget

    - name: Build brewtarget
      command: make
        chdir=/home/{{brew_user}}/brewtarget/build/
        creates=/home/{{brew_user}}/brewtarget/build/src/brewtarget
      become: false
      tags:
        - brewtarget

    - name: Install brewtarget
      command: make install
        chdir=/home/{{brew_user}}/brewtarget/build/
        creates=/home/{{brew_user}}/brewtarget/build/src/brewtarget
      tags:
        - brewtarget

    - name: Configure autofs.master
      lineinfile:
        line="/net -hosts nosuid"
        dest=/etc/auto.master
        state=present
      notify: restart autofs
      tags:
        - autofs

      #TODO: install a config file for brewtarget

    - name: Install BeerSmith prereqs
      apt:
        name={{item}}
        state=present
        update_cache=yes
      with_items:
        - libwebkitgtk-1.0-0
      tags:
        - beersmith


    - name: Install BeerSmith
      apt:
        deb=https://s3.amazonaws.com/beersmith2-3/BeerSmith-2.3.12_amd64.deb
      tags:
        - beersmith


  handlers:
    - name: restart autofs
      service:
        name: autofs
        state: restarted
# vim: ft=ansible
